from odoo import models, fields, api
class ContratoFornecedores(models.Model):
    _inherit= 'purchase.order_line'
    
    nota_empenho = fields.Many2one('x_nota_de_empenho', string = "Nota de Empenho")
    nota_reserva = fields.Char(related='nota_empenho.x_studio_nota_de_reserva', string="Nota de Reserva")
    ano_orcamento = fields.Char(related='nota_empenho._studio_ano_empenho', string="Exercicio")
    cod_orgao = fields.Many2one(related='nota_empenho.x_studio_orgao_empenho', string="Órgão")
    ds_orgao = fields.Char(related='nota_empenho.x_studio_cod_orgao_empenho', string='Nome Órgão')
    cod_poder = fields.Char(related='nota_empenho.x_studio_poder_empenho', string="Poder")
    ds_poder= fields.Char(related='nota_empenho.x_studio_nome_do_poder_empenho', string='Nome do Poder')
    cod_uo= fields.Char(related='nota_empenho.x_studio_unidade_oramentria_empenho', string='Unidade Orçamentária')
    ds_uo= fields.Char(related='nota_empenho.x_studio_nome_da_unidade_oramentria_empenho', string='Nome Unidade Orçamentária')
    cod_fonte= fields.Char(related='nota_empenho.x_studio_fonte_empenho', string='Fonte do Recurso')
    ds_fonte= fields.Char(related='nota_empenho.x_studio_nome_da_fonte_empenho', string='Nome da Fonte')
    cod_categoria = fields.Char(related='nota_empenho.x_studio_categoria_empenho', string='Categoria')
    nome_categoria = fields.Char(related='nota_empenho.x_studio_nome_da_categoria_empenho', string='Nome da Categoria')
    cod_classe= fields.Char(related='nota_empenho.x_studio_clase_empenho', string='Classe')
    nome_classe= fields.Char(related='nota_empenho.x_studio_nome_da_classe_empenho', string='Nome da Classe')
    cod_modalidade= fields.Char(related='nota_empenho.x_studio_modalidade_empenho', string='Modalidade')
    nome_modalidade= fields.Char(related='nota_empenho.x_studio_nome_da_modalidade_empenho', string='Nome da Modalidade')
    cod_grupo = fields.Char(related='nota_empenho.x_studio_grupo_empenho', string='Grupo')
    nome_grupo = fields.Char(related='nota_empenho.x_studio_nome_do_grupo_empenho', string='Nome do Grupo')
    cod_elemento = fields.Char(related='nota_empenho.x_studio_elemento_empenho', string='Elemento')
    ds_elemento = fields.Char(related='nota_empenho.x_studio_nome_do_elemento_empenho', string='Nome do Elemento')
    cod_funcao = fields.Char(related='nota_empenho.x_studio_funcao_empenho', string='Função')
    ds_funcao = fields.Char(related='nota_empenho.x_studio_nome_da_funcao_empenho', string='Nome da Função')
    cod_subfuncao= fields.Char(related='nota_empenho.x_studio_subfuncao_empenho', string='SunFunção')
    ds_subfuncao= fields.Char(related='nota_empenho.x_studio_nome_da_subfuncao_empenho', string='Nome da SubFunção')
    cod_programa= fields.Char(related='nota_empenho.x_studio_programa_empenho', string='Programa')
    ds_programa= fields.Char(related='nota_empenho.x_studio_nome_do_programa_empenho', string='Nome do Programa')
    cod_projeto_atividade= fields.Char(related='nota_empenho.x_studio_projeto_atividade_empenho', string='Projeto Atividade')
    ds_projeto_atividade= fields.Char(related='nota_empenho.x_studio_nome_do_projeto_atividade_empenho', string='Nome do Projeto')
    cod_ptres= fields.Char(related='nota_empenho.x_studio_cod_ptres_empenho', string='PTRES')
    programa_trabalho = fields.Char(related='nota_empenho.x_studio_programa_de_trabalho', string='Programa de Trabalho')
    cod_processo = fields.Char(related='nota_empenho.x_studio_processo', string='Processo')